// ============================================================
// GO INSPIRE NOW — Events Data
// ============================================================
// Add, edit, or remove events here. Dates in YYYY-MM-DD format.
// Categories: 'gatherings' | 'weekly-walks' | '25k-walk'

window.GIN_EVENTS = [

  // ── GATHERINGS ───────────────────────────────────────────
  {
    id: 'g1',
    category: 'gatherings',
    title: 'Brunch & Bloom',
    date: '2026-05-17',
    time: '10:00 AM',
    endTime: '12:30 PM',
    location: 'Milton Community Center',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'A morning of connection, great food, and community over brunch.',
    description: 'Join us for Brunch & Bloom — a special gathering for women to connect, share, and celebrate each other over a beautiful brunch spread. Expect warm conversations, an inspiring guest speaker, and a community that lifts you higher. Whether you come solo or bring a friend, you will leave feeling full — in every sense of the word.',
    whatToExpect: [
      'Complimentary brunch spread',
      'Inspiring guest speaker',
      'Community connection & networking time',
      'Door prizes & giveaways',
    ],
    howToPrep: [
      'Dress smart casual — come looking and feeling your best',
      'Bring a journal if you love to write',
      'Come solo or bring a friend — you will leave with new ones',
      'Arrive 10 minutes early for the best seating',
    ],
    cost: 0,
    paymentNote: null,
  },
  {
    id: 'g2',
    category: 'gatherings',
    title: 'Community Meetup Night',
    date: '2026-06-14',
    time: '6:00 PM',
    endTime: '8:30 PM',
    location: 'Faith Community Church Fellowship Hall',
    address: 'Pensacola, FL 32501',
    city: 'Pensacola, FL',
    shortDesc: 'An evening meetup for women to connect, share stories, and build community.',
    description: 'Community Meetup Night is a relaxed, welcoming evening for women at every stage of life. Come as you are, share where you are, and be encouraged by women who understand the journey. Light refreshments provided. Stories welcome. Judgment-free zone guaranteed.',
    whatToExpect: [
      'Light refreshments & snacks',
      'Open sharing circle',
      'Guest testimony / speaker',
      'Warm, welcoming atmosphere',
    ],
    howToPrep: [
      'Come as you are — this is a safe, casual space',
      'Bring something to share if you feel led (food, a quote, a story)',
      'Arrive ready to connect — leave your walls at the door',
    ],
    cost: 0,
    paymentNote: null,
  },
  {
    id: 'g3',
    category: 'gatherings',
    title: 'Summer Sip & Connect',
    date: '2026-07-12',
    time: '11:00 AM',
    endTime: '1:30 PM',
    location: 'Waterfront Park Pavilion',
    address: 'Fort Walton Beach, FL 32548',
    city: 'Fort Walton Beach, FL',
    shortDesc: 'Outdoor waterfront gathering — good vibes, great women, summer energy.',
    description: 'Take the gathering outside! Summer Sip & Connect is our warm-weather edition — a waterfront meetup full of good energy, refreshing drinks, and women who inspire. Bring your sunglasses and your smile. This one is all about joy.',
    whatToExpect: [
      'Outdoor waterfront setting',
      'Refreshments & light bites',
      'Lawn games & activities',
      'Community connection time',
    ],
    howToPrep: [
      'Dress for summer — light, comfortable, weather-ready',
      'Bring a reusable water bottle',
      'Wear sunscreen — we will be outside',
      'Bring lawn chairs if you have them (optional)',
    ],
    cost: 0,
    paymentNote: null,
  },
  {
    id: 'g4',
    category: 'gatherings',
    title: 'Fall Harvest Brunch',
    date: '2026-09-20',
    time: '10:00 AM',
    endTime: '1:00 PM',
    location: 'The Garden Room Event Space',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'Celebrate the season of harvest — reflecting on growth, gratitude, and community.',
    description: 'As the year winds down, we come together to celebrate how far we have come. The Fall Harvest Brunch is a time of reflection, gratitude, and community. We will honor the women who showed up, grew up, and kept going — all year long.',
    whatToExpect: [
      'Full brunch spread',
      'Year-in-review celebration',
      'Community awards & recognition',
      'Guest speaker & worship moment',
    ],
    howToPrep: [
      'Dress your best — this one is a celebration',
      'Come ready to reflect on your year',
      'Bring a sister who needs to be celebrated',
      'RSVP early — this event fills up fast',
    ],
    cost: 0,
    paymentNote: null,
  },

  // ── WEEKLY WALKS ($5) ──────────────────────────────────────
  {
    id: 'w1',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-04-26',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Riverwalk Park',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'Weekly walk (6–10 miles) — move your body, clear your mind, build your tribe.',
    description: 'Our Saturday Morning Walk is the heartbeat of the Go Inspire Now movement. Every week we lace up, show up, and walk together — 6 to 10 miles through beautiful local routes. It is more than a walk. It is a weekly reset, a community ritual, and a reminder that forward motion changes everything. $5 reserves your spot.',
    whatToExpect: [
      '6 to 10 mile neighborhood route',
      'Warm-up exercises before we roll out',
      'Cool-down stretch at the finish',
      'Community sharing circle at the end',
      'Good music, good people, good vibes',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Wear comfortable walking shoes (no flip flops)',
      'Bring a water bottle — hydration is non-negotiable',
      'Dress in layers — morning temps can be cool',
      'Arrive 5-10 minutes early for warm-up',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },
  {
    id: 'w2',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-05-03',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Riverwalk Park',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'Weekly walk (6–10 miles) — move your body, clear your mind, build your tribe.',
    description: 'Our Saturday Morning Walk is the heartbeat of the Go Inspire Now movement. Every week we lace up, show up, and walk together — 6 to 10 miles through beautiful local routes. It is more than a walk. It is a weekly reset, a community ritual, and a reminder that forward motion changes everything. $5 reserves your spot.',
    whatToExpect: [
      '6 to 10 mile neighborhood route',
      'Warm-up exercises before we roll out',
      'Cool-down stretch at the finish',
      'Community sharing circle at the end',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Wear comfortable walking shoes',
      'Bring a water bottle',
      'Arrive 5-10 minutes early for warm-up',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },
  {
    id: 'w3',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-05-10',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Bayfront Park',
    address: 'Pensacola, FL 32502',
    city: 'Pensacola, FL',
    shortDesc: 'Weekly walk (6–10 miles) along the beautiful Pensacola bayfront.',
    description: 'This week we head to the bayfront! Our Saturday Morning Walk keeps rolling — same energy, new scenery. Walk along Pensacola Bay with your sisters, breathe in the fresh air, and remind yourself: you keep going because you are worth it.',
    whatToExpect: [
      'Bayfront route (6 to 10 miles)',
      'Warm-up exercises at the start',
      'Cool-down and community circle at the finish',
      'Beautiful water views all route long',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Wear comfortable walking shoes',
      'Bring a water bottle',
      'Arrive 5-10 minutes early',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },
  {
    id: 'w4',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-05-17',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Riverwalk Park',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'Weekly walk (6–10 miles) — move your body, clear your mind, build your tribe.',
    description: 'Another Saturday, another opportunity to show up for yourself. Our Saturday Morning Walk continues — 6 to 10 miles, community, accountability, and motivation. See you on the trail.',
    whatToExpect: [
      '6 to 10 mile route',
      'Group warm-up and cool-down',
      'Community sharing circle',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Wear comfortable walking shoes',
      'Bring a water bottle',
      'Arrive 5-10 minutes early',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },
  {
    id: 'w5',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-05-24',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Sound Park',
    address: 'Navarre, FL 32566',
    city: 'Navarre, FL',
    shortDesc: 'Weekly walk (6–10 miles) — this week in Navarre at Sound Park.',
    description: 'We are walking in Navarre this week! Sound Park gives us a beautiful, peaceful route right along the water. Come walk, breathe, and connect with your community.',
    whatToExpect: [
      'Scenic waterfront route (6 to 10 miles)',
      'Group warm-up and cool-down',
      'Community sharing circle',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Wear comfortable walking shoes',
      'Bring a water bottle',
      'Arrive 5-10 minutes early',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },
  {
    id: 'w6',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-06-07',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Riverwalk Park',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'Weekly walk (6–10 miles) — summer sessions are here.',
    description: 'Summer is here and so are we. Our walks do not stop — they get stronger. Join us at Riverwalk for an energizing summer morning walk with your Go Inspire Now family.',
    whatToExpect: [
      '6 to 10 mile route',
      'Group warm-up and cool-down',
      'Community sharing circle',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Wear breathable, light clothing — it will be warm',
      'Bring extra water',
      'Arrive 5-10 minutes early',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },
  {
    id: 'w7',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-06-14',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Liza Jackson Park',
    address: 'Fort Walton Beach, FL 32548',
    city: 'Fort Walton Beach, FL',
    shortDesc: 'Weekly walk (6–10 miles) — this week along the beautiful Fort Walton shoreline.',
    description: 'Fort Walton Beach edition! We are walking Liza Jackson Park this week — one of the most scenic routes in our rotation. Come for the walk, stay for the view, leave inspired.',
    whatToExpect: [
      'Scenic coastal route (6 to 10 miles)',
      'Group warm-up and cool-down',
      'Community sharing circle',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Light, breathable clothing recommended',
      'Bring a water bottle and sunscreen',
      'Arrive 5-10 minutes early',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },
  {
    id: 'w8',
    category: 'weekly-walks',
    title: 'Saturday Morning Walk',
    date: '2026-06-21',
    time: '8:00 AM',
    endTime: '9:30 AM',
    location: 'Riverwalk Park',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'Weekly walk (6–10 miles) — back at our home base, Riverwalk Park.',
    description: 'Back home at Riverwalk! Our summer walk series keeps rolling. Show up, lace up, and move forward with your community.',
    whatToExpect: [
      '6 to 10 mile route',
      'Group warm-up and cool-down',
      'Community sharing circle',
    ],
    howToPrep: [
      'Reserve your spot by paying $5 via Cash App or PayPal',
      'Wear comfortable walking shoes',
      'Bring extra water — summer heat is real',
      'Arrive 5-10 minutes early',
    ],
    cost: 5,
    paymentNote: 'Pay $5 to reserve your spot via Cash App or PayPal before the walk.',
  },

  // ── 25K WALK ───────────────────────────────────────────────
  {
    id: 'k1',
    category: '25k-walk',
    title: 'Community 25K Walk',
    date: '2026-05-31',
    time: '7:00 AM',
    endTime: '12:00 PM',
    location: 'Pensacola Bay Area — Start: Bayfront Park',
    address: 'Pensacola, FL 32502',
    city: 'Pensacola, FL',
    shortDesc: 'Our flagship 25K walk — 15.5 miles of movement, community, and triumph.',
    description: 'The Community 25K Walk is Go Inspire Now\'s biggest event. This is where our weekly walkers prove to themselves what they are made of — 25 kilometers (15.5 miles) through the heart of Pensacola. Every step is a declaration: I showed up. I kept going. I inspired someone along the way. Aid stations, cheering squads, and a finish-line celebration await.',
    whatToExpect: [
      '25K (15.5 mile) scenic route through Pensacola',
      'Aid stations with water & snacks every 5K',
      'Go Inspire Now volunteer crew cheering you on',
      'Finish-line celebration with food, music & community',
      'Finisher recognition for every participant',
    ],
    howToPrep: [
      'Train for at least 4-6 weeks — work up to 10+ miles in your weekly walks',
      'Invest in broken-in, supportive walking shoes (not new ones)',
      'Bring a hydration pack or plan to use aid stations',
      'Pack light, high-energy snacks (nuts, bars, fruit)',
      'Dress in moisture-wicking layers you can remove',
      'Check in at the start line by 6:45 AM — 15 min before start',
      'Bring a friend — you will want someone at mile 12',
    ],
    cost: 0,
    paymentNote: null,
  },
  {
    id: 'k2',
    category: '25k-walk',
    title: 'Fall 25K Walk',
    date: '2026-10-11',
    time: '7:00 AM',
    endTime: '12:00 PM',
    location: 'Blackwater Heritage Trail — Start: Milton Trailhead',
    address: 'Milton, FL 32570',
    city: 'Milton, FL',
    shortDesc: 'Fall edition of our 25K — cooler temps, beautiful trail, maximum inspiration.',
    description: 'The wait for fall weather was worth it. Our Fall 25K takes us down the Blackwater Heritage Trail — one of the most beautiful walking paths in the Florida Panhandle. Cooler temperatures, stunning scenery, and your Go Inspire Now family beside you every step of the way. This is the walk of the year.',
    whatToExpect: [
      '25K (15.5 mile) trail route through Blackwater Heritage Trail',
      'Aid stations every 5K with water and snacks',
      'Gorgeous fall foliage scenery',
      'Finish-line celebration with food, music & recognition',
      'Finisher recognition for every participant',
    ],
    howToPrep: [
      'Train consistently through summer — our weekly walks are your training ground',
      'Trail-friendly shoes recommended (the path is mostly paved)',
      'Bring a hydration pack — trail aid stations are spaced further apart',
      'Pack snacks: nuts, energy bars, electrolyte packets',
      'Fall morning temps can be cool — layer up',
      'Check in at the start line by 6:45 AM',
    ],
    cost: 0,
    paymentNote: null,
  },

];
